port: 9992
# debug release(生产) test
run_mode: debug
# 多环境
business_log_count:
  default: sdf
  gc:
  test:

runtime_path: D:\go1\src\log\log\
match_regex: ([\d\.]+)\s+([^ \[]+)\s+([^ \[]+)\s+\[([^\]]+)\]\s+\"([^"]+)\"\s+(\d{3})\s+(\d+)\s+\"([^"]+)\"\s+\"([^"]+)\"\s+\"([^"]+)\"\s+\"([^"]+)\"\s+\"([^"]+)\"
# 1为固定文件 2 为动态根据日期分析前一天的日志
get_log_name_mode: 1
fixed_log_name: access.log
log_name_date_tpl: 20060102
# 日志文件名匹配正则生成规则,中间部分的%s会被替换为上面格式的当天的时间
log_name_reg: "*%s$"
db:
  name: gc_20190225
  addr: rm-2zedb141603k6dc8f5o.mysql.rds.aliyuncs.com:3306
  username: dbproxy
  password: Jybd2018$!
log:
  # 日志输出类型 file:文件 console: 控制台
  out_type: console
  file_name: log.log